Issue400 just scalafmt formated
microsoft/hyperspace pull request #412
Opened 2021-04-09 13:58 UTC by dmytroDragan

### What is the context for this pull request?

 - **Tracking Issue**: issue400
 - **Parent Issue**:  N/A
 - **Dependencies**: N/A

### What changes were proposed in this pull request?

Files (which were changed in https://github.com/microsoft/hyperspace/pull/402) were missing scalafmt formatting.
As result PR-402 is hard to review due to mix of issue fix and scalafmt formatting.

To resolve it, the simplest approach is to apply scalafmt formatting in first place. 
After merging this PR PR-402 should be unblocked.

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

No need

2021-04-10 02:45 UTC, sezruby commented
Could you confirm that this was from `hyperspace/dev/.scalafmt.conf`?

2021-04-10 07:27 UTC, sezruby reviewed
Generally looks good to me (if it's formatted with `hyperspace/dev/.scalafmt.conf`), but I'm not sure about the rearrangement part. (maybe it's intelliJ default?) cc @imback82 do we have any arrangement rule?

2021-04-14 06:20 UTC, dmytroDragan commented
Hi @sezruby!  It's formatted with hyperspace/dev/.scalafmt.conf

2021-04-14 06:50 UTC, sezruby commented
@dmytroDragan could you revert changes from "rearrangement"? 
I think the current arrangement looks better especially for `IndexLogEntry`, tag related functions / variable.
As we don't have a specific rule for arrangement for now, let's let that part so that we could merge this change quickly.

2021-04-14 07:52 UTC, andrei-ionescu requested changes
I did reviewing after 4-5 times where I did check how `scalafmt` reformatting is applied in my IDE and I can say that all these changes are not needed.

If we would add these changes, that it would mean that when I would apply reformatting on this file on my side, I'll be back to the original version with lots of formatting changes.

I recommend the you double check your formatting settings.

As I already posted on another of your PRs...

>Here is my `scalafmt` setup in IntelliJ Idea (I have `1.5.1` version):
>
><img width="627" alt="hyperspace_scalafmt" src="https://user-images.githubusercontent.com/3389505/114173887-8566de00-9940-11eb-9954-07189c0950b5.png">
>
>I usually do `Command+Shift+Alt+L` to reformat the file and use the following options in the dialog box:
>
><img width="306" alt="hyperspace_reformat" src="https://user-images.githubusercontent.com/3389505/114174070-c8c14c80-9940-11eb-9386-6718cc1d010d.png">

If you use IntelliJ IDEA we can review other settings too so that you get it right. I've been through similar issues where applying formatting but after a few retries I managed to make it work and have as less possible changes into PRs due to formatting.

2021-04-14 07:52 UTC, andrei-ionescu commented on src/main/scala/com/microsoft/hyperspace/index/IndexLogEntry.scala
> +        size.equals(that.size) &&
This is not scalafmt. I applied styling on the code and here it looks like this:

```
  override def equals(o: Any): Boolean = o match {
    case that: FileInfo =>
      name.equals(that.name) &&
      size.equals(that.size) &&
      modifiedTime.equals(that.modifiedTime)
    case _ => false
  }
```

No extra spaces.

Please check your `scalafmt`.

2021-04-14 07:52 UTC, andrei-ionescu commented on src/main/scala/com/microsoft/hyperspace/index/IndexLogEntry.scala
> +  case class Properties(
Same here. No changes required. Here is how this part looks after I applied `scalafmt` reformat command:

```
object CoveringIndex {
  case class Properties(columns: Properties.Columns,
    schemaString: String,
    numBuckets: Int,
    properties: Map[String, String])

  object Properties {
    case class Columns(indexed: Seq[String], included: Seq[String])
  }
}
```

No changes.

2021-04-14 07:52 UTC, andrei-ionescu commented on src/main/scala/com/microsoft/hyperspace/index/IndexLogEntry.scala
> +case class Update(appendedFiles: Option[Content] = None, deletedFiles: Option[Content] = None)
Same here. I don't have any changes.

Please check you formatting settings.

2021-04-14 07:52 UTC, andrei-ionescu commented on src/main/scala/com/microsoft/hyperspace/index/IndexLogEntry.scala
> +    copy(source = source.copy(plan = source.plan.copy(properties = source.plan.properties.copy(
Neither here - I don't have any changes after applying the reformatting.

2021-04-14 12:48 UTC, dmytroDragan commented
Th problem was with 1.5.1  vs 2.7.5 scalafmt.
https://github.com/microsoft/hyperspace/pull/418

2021-04-14 12:48 UTC, closed without merging